[package]
name = "prezent_contract_starknet"
version = "0.1.0"

[dependencies]
starknet = ">=1.0.0"

erc721 = { path = "erc721" }
factory = { path = "factory" }


[[target.starknet-contract]]

[scripts]
build = "protostar build"
test= "protostar test"

